export const ADD_SPENT = 'ADD_SPENT';
export const ADD_BUDGET = 'ADD_BUDGET';
export const REFRESH_BUDGET = 'REFRESH_BUDGET';
export const REMOVE_SPENT = 'REMOVE_SPENT';
export const REMOVE_SPENT_BY_ID = 'REMOVE_SPENT_BY_ID';
export const UPDATE_AMOUNT_OF_SPENT = 'UPDATE_AMOUNT_OF_SPENT';
export const UPDATE_AMOUNT_0F_BUDGET = 'UPDATE_AMOUNT_0F_BUDGET';
export const SUBTRACT_AMOUNT_OF_BUDGET = 'SUBTRACT_AMOUNT_OF_BUDGET';